if [ "${INCLUDE_GBOS_SH+is_defined}" ]; then
	return
fi
INCLUDE_GBOS_SH=true

. include/gb.sh

GBOS_WX_DEF=00
GBOS_WY_DEF=00

# ウィンドウの見かけ上の幅/高さ
# (描画用の1タイル分の幅/高さは除く)
GBOS_WIN_WIDTH_T=$(calc16_2 "${GB_DISP_WIDTH_T}-2")
GBOS_WIN_HEIGHT_T=$(calc16_2 "${GB_DISP_HEIGHT_T}-2")
GBOS_WIN_DRAWABLE_WIDTH_T=$(calc16_2 "${GBOS_WIN_WIDTH_T}-2")
GBOS_WIN_DRAWABLE_HEIGHT_T=$(calc16_2 "${GBOS_WIN_HEIGHT_T}-3")
GBOS_WIN_DRAWABLE_BASE_XT=$(calc16_2 "${GBOS_WX_DEF}+2")
GBOS_WIN_DRAWABLE_MAX_XT=$(calc16_2 "${GBOS_WIN_DRAWABLE_BASE_XT}+${GBOS_WIN_DRAWABLE_WIDTH_T}-1")
GBOS_WIN_DRAWABLE_BASE_YT=$(calc16_2 "${GBOS_WY_DEF}+3")
GBOS_WIN_DRAWABLE_MAX_YT=$(calc16_2 "${GBOS_WIN_DRAWABLE_BASE_YT}+${GBOS_WIN_DRAWABLE_HEIGHT_T}-1")
